### ISSUE TITLE
TotalPages field is not set

### ISSUE THREAD

**Issue by diego-vergara** [tmacharia/linq-paginator#4]
Hi, I used this library for my project, but the field TotalPages not work correctly. I found the field is not set, in **ProcessPagination** method:

https://github.com/tmacharia/linq-paginator/blob/d981085c618a3355f8348f393ba9a9a2a3ccb7a5/Paginator/Paginator.cs#L179-L185

Thank you

**Comment by tmacharia** [comment]
Hi @diego-vergara, thanks for notifying about the issue. 
This issue is now fixed in this pull request #6 
https://github.com/tmacharia/linq-paginator/blob/6029eeff4967f40e563740fe133b37f6205d8267/Paginator/Paginator.cs#L381-L389

**Comment by tmacharia** [comment]
Tested it out & it now works fine. 
Closing this issue.
